# Generated by Django 4.2.16 on 2024-09-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensiveTracker', '0002_rename_current_location_transaction_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='upi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
